#!/bin/bash

SOURCE=camera
PRINTER=MFC5840CN

COPYRIGHT="(C) 2008 East Lancashire Scouts"

PAGE_X=`identify -format "%w" base/Calendar.png`
PAGE_Y=`identify -format "%h" base/Calendar.png`

function process_file() {
	INFILE=$1
	OUTFILE=$2

	echo "Processing $INFILE ..."

	echo "Resizing Photograph ..."
	convert $INFILE -resize 2050! temp1.png

	X=`identify -format "%w" temp1.png`
	Y=`identify -format "%h" temp1.png`

	X_OFFSET=$((($PAGE_X-$X)/2))
	Y_OFFSET=$((2000-$Y))

	TXTSIZE=$(($Y/8))
	SHADOW=$(($TXTSIZE/10))
	FOOTER=$(($TXTSIZE/8))

	echo "Merging Images ..."
	composite -compose Over temp1.png -geometry +$X_OFFSET+$Y_OFFSET base/Calendar.png temp2.png
	composite -compose Over base/Header.png temp2.png temp3.png

	echo "Adding Footer Text ..."
	convert temp3.png \
		-fill green -font Helvetica-Narrow -pointsize $FOOTER \
		-draw "gravity south-west text 210,50 '$OUTFILE'" \
		-draw "gravity south-east text 210,50 '$COPYRIGHT'" \
		temp4.png

	echo "Preparing PDf ..."
	convert -page A4 -units PixelsPerInch -density 72 temp4.png $OUTFILE

	echo -n "Printing $OUTFILE: "
#	lp -d$PRINTER $OUTFILE
	rm temp1.png temp2.png temp3.png temp4.png
	}


for day in Monday Tuesday Wednesday Thursday Friday Saturday ; do
  for infile in outfiles/$day/* ; do
    outfile=`echo $infile | sed 's/.jpeg/.pdf/
				 s/outfiles/pdf/'`
    process_file $infile $outfile
  done
done

